<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260224224225 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE client (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, dni VARCHAR(255) NOT NULL, full_name VARCHAR(255) NOT NULL, address TEXT NOT NULL, phone VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE role (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_57698A6A5E237E06 ON role (name)');
        $this->addSql('CREATE TABLE service (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(255) NOT NULL, install_address TEXT NOT NULL, status VARCHAR(255) NOT NULL, client_id INT DEFAULT NULL, discr VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E19D9AD219EB6921 ON service (client_id)');
        $this->addSql('CREATE TABLE service_ftth (ont_mac VARCHAR(17) NOT NULL, pon_port VARCHAR(50) NOT NULL, splitter_id VARCHAR(50) NOT NULL, optical_power NUMERIC(5, 2) NOT NULL, id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE service_wimax (antenna_ip VARCHAR(45) NOT NULL, antenna_mac VARCHAR(17) NOT NULL, ap_name VARCHAR(255) NOT NULL, signal_strength INT NOT NULL, id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE ticket (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, priority VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL, subject TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, service_id INT DEFAULT NULL, creator_id INT NOT NULL, assigned_role_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_97A0ADA3ED5CA9E6 ON ticket (service_id)');
        $this->addSql('CREATE INDEX IDX_97A0ADA361220EA6 ON ticket (creator_id)');
        $this->addSql('CREATE INDEX IDX_97A0ADA3DC9B9A23 ON ticket (assigned_role_id)');
        $this->addSql('CREATE TABLE ticket_comment (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, comment TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ticket_id INT NOT NULL, creator_user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_98B80B3E700047D2 ON ticket_comment (ticket_id)');
        $this->addSql('CREATE INDEX IDX_98B80B3E29FC6AE1 ON ticket_comment (creator_user_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, password VARCHAR(255) NOT NULL, user_role_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_8D93D6498E0E3CA6 ON "user" (user_role_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE service ADD CONSTRAINT FK_E19D9AD219EB6921 FOREIGN KEY (client_id) REFERENCES client (id)');
        $this->addSql('ALTER TABLE service_ftth ADD CONSTRAINT FK_AA88563BBF396750 FOREIGN KEY (id) REFERENCES service (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE service_wimax ADD CONSTRAINT FK_BB6537BF396750 FOREIGN KEY (id) REFERENCES service (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ticket ADD CONSTRAINT FK_97A0ADA3ED5CA9E6 FOREIGN KEY (service_id) REFERENCES service (id)');
        $this->addSql('ALTER TABLE ticket ADD CONSTRAINT FK_97A0ADA361220EA6 FOREIGN KEY (creator_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ticket ADD CONSTRAINT FK_97A0ADA3DC9B9A23 FOREIGN KEY (assigned_role_id) REFERENCES role (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ticket_comment ADD CONSTRAINT FK_98B80B3E700047D2 FOREIGN KEY (ticket_id) REFERENCES ticket (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ticket_comment ADD CONSTRAINT FK_98B80B3E29FC6AE1 FOREIGN KEY (creator_user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT FK_8D93D6498E0E3CA6 FOREIGN KEY (user_role_id) REFERENCES role (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE service DROP CONSTRAINT FK_E19D9AD219EB6921');
        $this->addSql('ALTER TABLE service_ftth DROP CONSTRAINT FK_AA88563BBF396750');
        $this->addSql('ALTER TABLE service_wimax DROP CONSTRAINT FK_BB6537BF396750');
        $this->addSql('ALTER TABLE ticket DROP CONSTRAINT FK_97A0ADA3ED5CA9E6');
        $this->addSql('ALTER TABLE ticket DROP CONSTRAINT FK_97A0ADA361220EA6');
        $this->addSql('ALTER TABLE ticket DROP CONSTRAINT FK_97A0ADA3DC9B9A23');
        $this->addSql('ALTER TABLE ticket_comment DROP CONSTRAINT FK_98B80B3E700047D2');
        $this->addSql('ALTER TABLE ticket_comment DROP CONSTRAINT FK_98B80B3E29FC6AE1');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT FK_8D93D6498E0E3CA6');
        $this->addSql('DROP TABLE client');
        $this->addSql('DROP TABLE role');
        $this->addSql('DROP TABLE service');
        $this->addSql('DROP TABLE service_ftth');
        $this->addSql('DROP TABLE service_wimax');
        $this->addSql('DROP TABLE ticket');
        $this->addSql('DROP TABLE ticket_comment');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
